#!/usr/bin/expect -f
set timeout 300
spawn ssh -o PreferredAuthentications=password -o StrictHostKeyChecking=no panel-prosuite
expect "password:"
send "Pp55202104#\r"
expect "$ "
send "sudo -S docker run --rm -v /opt/vendetta:/app -w /app node:20-alpine sh -c \"npx prisma db push --accept-data-loss --url file:prisma/prod.db\"\r"
expect "password"
send "Pp55202104#\r"
expect "Done"
send "exit\r"
expect eof
