CREATE INDEX IF NOT EXISTS "MusicianProfile_status_idx" ON "MusicianProfile"("status");
CREATE INDEX IF NOT EXISTS "Substitute_musicianProfileId_idx" ON "Substitute"("musicianProfileId");
CREATE INDEX IF NOT EXISTS "PackageService_packageId_idx" ON "PackageService"("packageId");
CREATE INDEX IF NOT EXISTS "Quote_clientId_idx" ON "Quote"("clientId");
CREATE INDEX IF NOT EXISTS "Quote_status_idx" ON "Quote"("status");
CREATE INDEX IF NOT EXISTS "QuoteItem_quoteId_idx" ON "QuoteItem"("quoteId");
CREATE INDEX IF NOT EXISTS "Event_clientId_idx" ON "Event"("clientId");
CREATE INDEX IF NOT EXISTS "Event_locationId_idx" ON "Event"("locationId");
CREATE INDEX IF NOT EXISTS "Event_packageId_idx" ON "Event"("packageId");
CREATE INDEX IF NOT EXISTS "Event_bandEventId_idx" ON "Event"("bandEventId");
CREATE INDEX IF NOT EXISTS "Event_date_idx" ON "Event"("date");
CREATE INDEX IF NOT EXISTS "Event_status_idx" ON "Event"("status");
CREATE INDEX IF NOT EXISTS "EventMusician_eventId_idx" ON "EventMusician"("eventId");
CREATE INDEX IF NOT EXISTS "EventMusician_musicianId_idx" ON "EventMusician"("musicianId");
CREATE INDEX IF NOT EXISTS "Payment_eventId_idx" ON "Payment"("eventId");
CREATE INDEX IF NOT EXISTS "Payment_bookingRequestId_idx" ON "Payment"("bookingRequestId");
CREATE INDEX IF NOT EXISTS "Payment_status_idx" ON "Payment"("status");
CREATE INDEX IF NOT EXISTS "Contract_eventId_idx" ON "Contract"("eventId");
CREATE INDEX IF NOT EXISTS "Notification_eventId_idx" ON "Notification"("eventId");
CREATE INDEX IF NOT EXISTS "Notification_bookingRequestId_idx" ON "Notification"("bookingRequestId");
CREATE INDEX IF NOT EXISTS "Notification_status_idx" ON "Notification"("status");
CREATE INDEX IF NOT EXISTS "Notification_createdAt_idx" ON "Notification"("createdAt");
CREATE INDEX IF NOT EXISTS "BookingRequest_clientId_idx" ON "BookingRequest"("clientId");
CREATE INDEX IF NOT EXISTS "BookingRequest_packageId_idx" ON "BookingRequest"("packageId");
CREATE INDEX IF NOT EXISTS "BookingRequest_status_idx" ON "BookingRequest"("status");
CREATE INDEX IF NOT EXISTS "BookingRequest_status_createdAt_idx" ON "BookingRequest"("status", "createdAt");
CREATE INDEX IF NOT EXISTS "Rehearsal_locationId_idx" ON "Rehearsal"("locationId");
CREATE INDEX IF NOT EXISTS "Rehearsal_datetime_idx" ON "Rehearsal"("datetime");
CREATE INDEX IF NOT EXISTS "RehearsalSong_rehearsalId_idx" ON "RehearsalSong"("rehearsalId");
CREATE INDEX IF NOT EXISTS "RehearsalSong_songId_idx" ON "RehearsalSong"("songId");
CREATE INDEX IF NOT EXISTS "RehearsalMusician_rehearsalId_idx" ON "RehearsalMusician"("rehearsalId");
CREATE INDEX IF NOT EXISTS "RehearsalMusician_musicianId_idx" ON "RehearsalMusician"("musicianId");
CREATE INDEX IF NOT EXISTS "SetlistSong_setlistId_idx" ON "SetlistSong"("setlistId");
CREATE INDEX IF NOT EXISTS "SetlistSong_songId_idx" ON "SetlistSong"("songId");
CREATE INDEX IF NOT EXISTS "InboxItem_status_idx" ON "InboxItem"("status");
CREATE INDEX IF NOT EXISTS "InboxItem_clientId_idx" ON "InboxItem"("clientId");
CREATE INDEX IF NOT EXISTS "InboxItem_bookingRequestId_idx" ON "InboxItem"("bookingRequestId");
CREATE INDEX IF NOT EXISTS "InboxItem_createdAt_idx" ON "InboxItem"("createdAt");

-- Add today reminder fields to GlobalConfig
ALTER TABLE "GlobalConfig" ADD COLUMN IF NOT EXISTS "msgTodayReminderActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "GlobalConfig" ADD COLUMN IF NOT EXISTS "msgTemplateTodayReminder" TEXT;

